'use strict';

// tests for userGet
// Generated by serverless-mocha-plugin

const mod = require('../src/user/get.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'index' });

