language: node_js
node_js:
  - '4.3'

before_install:
  - mysql -u root -e 'CREATE DATABASE the_fans_test;'
  - npm i -g serverless
  - npm install serverless-mocha-plugin

before_script:
  - npm run migrate-test

services:
  - mysql

script:
  - npm test

#script: sls deploy