language: node_js
node_js:
  - '4.3'

before_install:
  - mysql -u root -e 'CREATE DATABASE the-fans;'
  - npm i -g serverless

before_script:
  - ./node_modules/sequelize-cli/bin/sequelize db:migrate

services:
  - mysql


#script: sls deploy