service: the-fans-api
provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true
  environment:
    THE_FANS:
      db:
        host: 127.0.0.1
        user: travis
        password: ${env:FUNC_PREFIX}
        database: the-fans
  timeout: 10
  memorySize: 128
package:
  individually: true
  exclude:
    - node_modules/**
    - .idea/**
    - .git/**
    - events/**
    - coverage/**
    - bin/**
    - test/**
    - config/**
plugins:
  - serverless-aws-documentation
  - serverless-mocha-plugin
  - serverless-offline
  - serverless-plugin-aws-alerts
  - serverless-crypt
  - serverless-plugin-browserify
  - serverless-plugin-cloudwatch-sumologic
  - serverless-plugin-diff
  - serverless-plugin-include-dependencies
  - serverless-plugin-optimize
functions:
  userPut:
    handler: src/user/put.index
  userGet:
    handler: src/user/get.index
  hello:
    handler: handler.hello
